---
dependencies:
  - name: rabbitmq
    version: 6.15.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: rabbitmq.install
  - name: postgresql
    version: 8.0.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.install
  - name: memcached
    version: 3.2.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: memcached.install
