{{- if eq .Values.target "local" -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "awx.fullname" . }}-postgres-volume
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data_dor"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "awx.fullname" . }}-rabbitmq-volume
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/rabbit_dor"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "awx.fullname" . }}-gogs-volume
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/gogs_dor"

{{- end -}}