{{- if and (eq .Values.target "rancher") (.Values.certificate.crt) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "awx.fullname" . }}-certificate
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get .Values.certificate.crt | b64enc }}
  tls.key: {{ .Files.Get .Values.certificate.key | b64enc }}
{{- end }}
