apiVersion: v1
kind: Service
metadata:
  name: {{ template "awx.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "awx.name" . }}-web
    helm.sh/chart: {{ include "awx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8052
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "awx.name" . }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "awx.fullname" . }}-gogs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "awx.name" . }}-gogs
    helm.sh/chart: {{ include "awx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "awx.name" . }}-gogs
    app.kubernetes.io/instance: {{ .Release.Name }}
