---

- name: Wait for AWX setup to end
  uri:
    url: "{{ awx.uri }}/"
    method: GET
    status_code: 200, 302
    follow_redirects: none
    validate_certs: "{{ validate_certs }}"
  retries: 20
  delay: 10
  register: is_awx_up
  until: is_awx_up.status == 200
  when: control.setup_awx == true

- name: Little pause for contingency
  pause:
    seconds: 2
  when:
    - control.setup_awx == true
    - is_awx_up.attempts > 1

- name: Create token
  uri:
    url: "{{ awx.uri }}/api/v2/tokens/"
    user: "{{ awx.user }}"
    password: "{{ awx.password }}"
    force_basic_auth: true
    validate_certs: "{{ validate_certs }}"
    method: POST
    status_code: 201
    follow_redirects: all
    body_format: json
    body:
      description: "AWX Setup"
      application: null
      scope: "write"
  register: awx_token

- set_fact:
    awx:
      uri: "{{ awx.uri }}"
      token: "{{ awx_token.json.token }}"
      user: "{{ awx.user }}"
