---

- hosts: localhost
  tasks:
    - include_vars:
        file: inventory.yml

    - debug:
        msg: "Starting deployment on environment {{ environment_name }}; AWX URL is {{ awx.uri }}"

    - block:
      - name: spin up containers
        docker_compose:
          project_src: "{{ compose.path }}"
        register: docker_spin_up

      - name: wait for web servers to start
        pause:
          seconds: 20
        when: docker_spin_up.changed == true
      when: control.setup_awx == true and deployment_type == 'docker'

    - name: Create or update helm chart
      include_role:
        name: kubernetes
      when: control.setup_awx == true and deployment_type == 'k8s'

    - name: Setup Gogs
      include_role:
        name: gogs
      vars:
        action: install

    - name: Get Gogs token
      include_role:
        name: gogs
      vars:
        action: token

    - name: Setup AWX and get token
      include_role:
        name: setup_awx

    - block:
      - include_role:
          name: git
        vars:
          action: create

      - include_role:
          name: git
        vars:
          action: synchronize
      when: control.fill_gogs is not defined or control.fill_gogs == true

    - name: Fill AWX
      include_role:
        name: fill_awx
      when: control.fill_awx is not defined or control.fill_awx == true

    - name: run tests
      include_role:
        name: tests
      when: control.test_awx == true

    - name: remove token used for installation
      uri:
        url: "{{ awx.uri }}{{ awx_token.json.url }}"
        headers:
          Authorization: Bearer {{ awx.token }}
        validate_certs: "{{ validate_certs }}"
        method: DELETE
        status_code: 204
        follow_redirects: all

    - name: "check if tests have passed"
      fail:
        msg: "At least one test has failed. Please check test output."
      when:
        - awx_tests_result is defined
        - awx_tests_result == false
