---

- name: clean leftovers
  file:
    path: './repos'
    state: absent
    force: yes

- name: create repos directory
  file:
    path: './repos'
    state: directory

- name: ensure Git is configured
  shell: |
    git config --global http.sslVerify false
    git config --global user.email "VstsAgent@engie.com"
    git config --global user.name "VSTS Agent"
    git config --global push.default simple

- name: "synchronize repository {{ repository.key }}"
  include_tasks: synchronize_inner.yml
  vars:
    branch: "{{ gogs.source_branch }}"
  loop: "{{ gogs.sources | dict2items }}"
  loop_control:
    loop_var: repository

- name: clean everything
  file:
    path: './repos'
    state: absent
    force: yes
