---

- include_tasks: functions/create_awx_object.yml
  loop:
    - {
      variable: "{{ node_link.variable | default('workflow_link_nodes_link_var') }}", # Most of the time we aren't interrested in storing the node in a variable
      api: "workflow_job_template_nodes/{{ node_link.source.id }}/{{ node_link.type }}_nodes",
      search: {
        id: "{{ node_link.destination.id }}"
      },
      body: '{"id": {{ node_link.destination.id }}}'
    }
