---

- name: create workflow job templates for VM removal
  include_tasks: functions/create_awx_object.yml
  loop:
    - variable: 'delete_virtual_machine'
      api: 'workflow_job_templates'
      name: 'Delete Virtual Machine'
      body:
        name: "Delete Virtual Machine"
        description: ""
        extra_vars: ""
        organization: "{{ organisation.id }}"
        survey_enabled: true
        allow_simultaneous: true
        ask_variables_on_launch: false
        inventory: null
        ask_inventory_on_launch: false

- name: create survey for workflow job templates for VM removal
  uri:
    headers:
      Authorization: Bearer {{ awx.token }}
    url: "{{ awx.uri }}/api/v2/workflow_job_templates/{{ delete_virtual_machine.id }}/survey_spec/"
    validate_certs: "{{ validate_certs }}"
    method: POST
    body_format: json
    body: "{{ lookup('template','workflow_job_templates/delete_virtual_machine_survey.json') }}"

- name: create nodes for workflow job templates for VM removal
  include_tasks: functions/workflow_node.yml
  loop:
    - variable: 'unregister_vm_node'
      workflow: "{{ delete_virtual_machine }}"
      target: "{{ unregister_vm }}"
    - variable: 'delete_vm_node'
      workflow: "{{ delete_virtual_machine }}"
      target: "{{ delete_vm }}"
  loop_control:
    loop_var: node

- name: link nodes for workflow job templates for VM removal
  include_tasks: functions/workflow_link_nodes.yml
  loop:
    - { source: "{{ delete_vm_node }}", destination: "{{ unregister_vm_node }}", type: 'success' }
  loop_control:
    loop_var: node_link
