---

- name: create inventory
  include_tasks: functions/create_awx_object.yml
  loop:
    - variable: 'inventory'
      api: 'inventories'
      name: 'DevOpsRex inventory'
      body:
        name: "DevOpsRex inventory"
        description: "Contains all VM from Azure"
        organization: "{{ organisation.id }}"
        kind: ""
        host_filter: null
        variables: "---"
        insights_credential: null
    - variable: 'inventory_credential'
      api: credentials
      name: Azure
      body:
        name: "Azure"
        description: "Credentials used to connect to Azure"
        organization: "{{ organisation.id }}"
        credential_type: 11
        inputs:
          subscription: "{{ credentials.Azure.subscription }}"
          client: "{{ credentials.Azure.application_id }}"
          secret: "{{ credentials.Azure.application_secret }}"
          tenant: "{{ credentials.Azure.tenant }}"

- name: create inventory source
  include_tasks: functions/create_awx_object.yml
  loop:
    - variable: 'inventory_source'
      api: 'inventories/{{ inventory.id }}/inventory_sources'
      name: 'Azure'
      body: 
        name: "Azure"
        description: "Inventory source for Azure subscription"
        source: "azure_rm"
        source_path: ""
        source_script: null
        source_vars: ""
        credential: "{{ inventory_credential.id }}"
        source_regions: "westeurope"
        instance_filters: ""
        group_by: ""
        overwrite: true
        overwrite_vars: true
        timeout: 0
        verbosity: 1
        update_on_launch: false
        update_cache_timeout: 0
        source_project: null
        update_on_project_update: false

- name: Schedule inventory refresh
  include_tasks: functions/create_awx_object.yml
  loop:
    - api: 'inventory_sources/{{ inventory_source.id }}/schedules'
      name: 'Nightly refresh'
      body: 
        rrule: "DTSTART;TZID=Europe/Berlin:20190717T003000 RRULE:FREQ=DAILY;INTERVAL=1"
        name: "Nightly refresh"
        description: "every day"
        extra_data: {}
        inventory: null
        job_type: null
        diff_mode: null
        verbosity: null
        enabled: true
